//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from OctopusQL.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="OctopusQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IOctopusQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR([NotNull] OctopusQLParser.RContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect([NotNull] OctopusQLParser.SelectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhereClause([NotNull] OctopusQLParser.WhereClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.attributesWithDot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributesWithDot([NotNull] OctopusQLParser.AttributesWithDotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] OctopusQLParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.selectClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectClause([NotNull] OctopusQLParser.SelectClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclude([NotNull] OctopusQLParser.IncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.aggregateClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateClause([NotNull] OctopusQLParser.AggregateClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] OctopusQLParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] OctopusQLParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] OctopusQLParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.entity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity([NotNull] OctopusQLParser.EntityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.entityRep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityRep([NotNull] OctopusQLParser.EntityRepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OctopusQLParser.all"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll([NotNull] OctopusQLParser.AllContext context);
}
