//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from OctopusQL.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IOctopusQLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class OctopusQLBaseListener : IOctopusQLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR([NotNull] OctopusQLParser.RContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR([NotNull] OctopusQLParser.RContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.select"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect([NotNull] OctopusQLParser.SelectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.select"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect([NotNull] OctopusQLParser.SelectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.deleteSelect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteSelect([NotNull] OctopusQLParser.DeleteSelectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.deleteSelect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteSelect([NotNull] OctopusQLParser.DeleteSelectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.insert"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsert([NotNull] OctopusQLParser.InsertContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.insert"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsert([NotNull] OctopusQLParser.InsertContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.delete"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelete([NotNull] OctopusQLParser.DeleteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.delete"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelete([NotNull] OctopusQLParser.DeleteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.update"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpdate([NotNull] OctopusQLParser.UpdateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.update"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpdate([NotNull] OctopusQLParser.UpdateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.insertClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsertClause([NotNull] OctopusQLParser.InsertClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.insertClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsertClause([NotNull] OctopusQLParser.InsertClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.getClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetClause([NotNull] OctopusQLParser.GetClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.getClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetClause([NotNull] OctopusQLParser.GetClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.assignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignments([NotNull] OctopusQLParser.AssignmentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.assignments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignments([NotNull] OctopusQLParser.AssignmentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] OctopusQLParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] OctopusQLParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.whereClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhereClause([NotNull] OctopusQLParser.WhereClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.whereClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhereClause([NotNull] OctopusQLParser.WhereClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.fieldsWithDot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsWithDot([NotNull] OctopusQLParser.FieldsWithDotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.fieldsWithDot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsWithDot([NotNull] OctopusQLParser.FieldsWithDotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFields([NotNull] OctopusQLParser.FieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFields([NotNull] OctopusQLParser.FieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.entityReps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityReps([NotNull] OctopusQLParser.EntityRepsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.entityReps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityReps([NotNull] OctopusQLParser.EntityRepsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.selectClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectClause([NotNull] OctopusQLParser.SelectClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.selectClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectClause([NotNull] OctopusQLParser.SelectClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclude([NotNull] OctopusQLParser.IncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclude([NotNull] OctopusQLParser.IncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.aggregateClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregateClause([NotNull] OctopusQLParser.AggregateClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.aggregateClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregateClause([NotNull] OctopusQLParser.AggregateClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValues([NotNull] OctopusQLParser.ValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValues([NotNull] OctopusQLParser.ValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] OctopusQLParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] OctopusQLParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc([NotNull] OctopusQLParser.FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc([NotNull] OctopusQLParser.FuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] OctopusQLParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] OctopusQLParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] OctopusQLParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] OctopusQLParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntity([NotNull] OctopusQLParser.EntityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntity([NotNull] OctopusQLParser.EntityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.entityRep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityRep([NotNull] OctopusQLParser.EntityRepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.entityRep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityRep([NotNull] OctopusQLParser.EntityRepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OctopusQLParser.all"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAll([NotNull] OctopusQLParser.AllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OctopusQLParser.all"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAll([NotNull] OctopusQLParser.AllContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
